#!/usr/bin/python
#-*- coding:utf-8 -*-

# XXX this is only meant for testing
# do not yell about the bad code !

import sys
import time
from pychat import ChatServer

def main(argv):
	server = ChatServer()

	server.start()

	# XXX
	while True:
		try:
			time.sleep(1)
		except KeyboardInterrupt:
			server.stop()
			sys.exit(0)

if __name__ == "__main__":
	main(sys.argv)

